name: Build and Deploy Calendars

on:
  schedule:
    - cron: "0 3/6 * * *"   # cada hora (ejemplo)
  workflow_dispatch:
    inputs:
      force:
        description: 'Publicar incluso sin cambios'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # is_updated: ${{ steps.check_site_changes.outputs.site_updated }}
      is_updated: ${{ steps.site_changes.outputs.site_updated }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
          pip-install: -r requirements.txt

      - name: Generar calendarios
        run: |
          python genera_bisbe_calendar.py
          python genera_faf_calendar.py

      - name: Commit cambios
        id: site_changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add site/*.ics
          ( git commit -m 'Actualizar calendarios' && echo 'site_updated=true' >> $GITHUB_OUTPUT ) || echo "Sin cambios"
          git push

      - name: Subir artifact
        uses: actions/upload-pages-artifact@v4
        if: ${{ inputs.force || steps.site_changes.outputs.site_updated == 'true' }}
        with:
          path: site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.force || needs.build.outputs.is_updated == 'true' }}

    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # - name: Subir artifact
      #   uses: actions/upload-pages-artifact@v4
      #   with:
      #     path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
