name: Actualizar calendario

on:
  schedule:
    - cron: "0 3/6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - run: python genera_calendario.py

      - name: Commit cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add calendario.ics
          git commit -m "Actualizar calendario" || echo "Sin cambios"
          git push
